apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ops-pushgateway
  namespace: monitoring
  labels:
    ops: "true"
spec:
  selector:
    matchLabels:
      app: ops-pushgateway
  namespaceSelector:
    any: true
  endpoints:
    - port: metric
      interval: 30s
