apiVersion: v1
kind: Service
metadata:
  labels:
    app: ops-gpu-process-exporter
  name: ops-gpu-process-exporter
  namespace: monitoring
spec:
  ports:
  - name: metrics
    port: 9401
    protocol: TCP
    targetPort: 9401
  selector:
    app.kubernetes.io/name: process-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    tier: ops
  name: ops-gpu-process-exporter
  namespace: monitoring
spec:
  endpoints:
    - interval: 15s
      port: metrics
      metricRelabelings:
      # 只保留核心的 GPU 进程指标
      - action: keep
        regex: process_(gpu_utilization|gpu_memory_usage|sm_utilization|gpu_memory_total|command_line|process_count)
        sourceLabels:
        - __name__
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app: ops-gpu-process-exporter
  targetLabels:
    - tier
