apiVersion: v1
kind: Service
metadata:
  name: ops-juicefs-monitor
  namespace: default
  labels:
    app: juicefs
spec:
  selector:
    app: juicefs
  ports:
  - name: metrics
    port: 15275
    targetPort: 15275
    protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    tier: ops
  name: ops-juicefs
  namespace: monitoring
spec:
  namespaceSelector:
    any: true
  endpoints:
  - port: metrics
    interval: 15s
    scheme: http
    path: /metrics
    metricRelabelings:
    # 只保留核心的 JuiceFS 指标
    - action: keep
      regex: juicefs_(used_space|used_inodes|cpu_usage|memory_usage|object_request_durations.*|blockcache_.*|fuse_.*_durations.*|transaction_durations.*)
      sourceLabels:
      - __name__
  selector:
    matchLabels:
      app: juicefs
