apiVersion: v1
kind: Service
metadata:
  labels:
    app: ops-process-exporter
  name: ops-process-exporter
  namespace: monitoring
spec:
  ports:
  - name: metrics
    port: 9256
    protocol: TCP
    targetPort: 9256
  selector:
    app: process-exporter-daemonset
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    ops: "true"
  name: ops-process-exporter
  namespace: monitoring
spec:
  endpoints:
  - interval: 60s
    port: metrics
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app: ops-process-exporter
  targetLabels:
  - tier
