apiVersion: v1
kind: Endpoints
metadata:
  name: ops-fdb-exporter
  namespace: monitoring
  labels:
    app: ops-fdb-exporter
subsets:
  - addresses:
      - ip: 10.0.0.1
    ports:
      - name: metrics
        port: 9444
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ops-fdb-exporter
  namespace: monitoring
  labels:
    app: ops-fdb-exporter
spec:
  ports:
    - name: metrics
      port: 9444
      targetPort: 9444
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ops-fdb
  namespace: monitoring
  labels:
    ops: "true"
spec:
  selector:
    matchLabels:
      app: ops-fdb-exporter
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      relabelings:
        - sourceLabels: [__address__]
          targetLabel: job
          regex: '([^:]+)(?::\d+)?'
          replacement: 'fdb-exporter-$1'
          action: replace
