apiVersion: v1
kind: Service
metadata:
  labels:
    app: ops-process-exporter
  name: ops-process-exporter
  namespace: monitoring
spec:
  ports:
  - name: metrics
    port: 9256
    protocol: TCP
    targetPort: 9256
  selector:
    app: process-exporter-daemonset
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    tier: ops
  name: ops-process-exporter
  namespace: monitoring
spec:
  endpoints:
  - interval: 60s
    port: metrics
    metricRelabelings:
    # 只保留核心的进程指标
    - action: keep
      regex: namedprocess_(namegroup_cpu_seconds_total|namegroup_memory_bytes|namegroup_num_procs|namegroup_open_filedesc|namegroup_read_bytes_total|namegroup_write_bytes_total)
      sourceLabels:
      - __name__
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app: ops-process-exporter
  targetLabels:
  - tier
