apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ops-smartctl-exporter
  namespace: monitoring
  labels:
    ops: "true"
    app.kubernetes.io/name: prometheus-smartctl-exporter
spec:
  podMetricsEndpoints:
    - interval: 30s
      scrapeTimeout: 10s
      port: http
      scheme: http
      path: /metrics
      honorLabels: false
      honorTimestamps: false
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-smartctl-exporter
