apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    ops: "true"
    app.kubernetes.io/name: ops-ix-exporter
    app.kubernetes.io/part-of: kube-prometheus
  name: ops-ix-exporter
  namespace: monitoring
spec:
  podMetricsEndpoints:
    - interval: 30s
      scrapeTimeout: 10s
      port: metrics
      scheme: http
      path: /metrics
      honorLabels: false
      honorTimestamps: false
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/name: ix-exporter
