---
apiVersion: v1
kind: Secret
metadata:
  name: remote-storage-keys
  namespace: monitoring
  labels:
    app: vm-operator
type: Opaque
stringData:
  credentials: |-
    [default]
    aws_access_key_id = your_access_key_id
    aws_secret_access_key = your_secret_access_key
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: example-vmsingle
  namespace: monitoring
spec:
  # Add fields here
  retentionPeriod: "1"
  vmBackup:
    acceptEULA: true
    destination: "s3://bucket/path/to/backup/dir"
    credentialsSecret:
      name: remote-storage-keys
      key: credentials